-- Users Table: Stores authentication and profile data
-- [cite: 35] User Profile: Stores academic level and preference
CREATE TABLE IF NOT EXISTS users (
    user_id SERIAL PRIMARY KEY, -- Use INTEGER PRIMARY KEY AUTOINCREMENT for SQLite
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Quizzes Table: Metadata for generated quizzes
--  Data Persistence: All generated quizzes are stored
CREATE TABLE IF NOT EXISTS quizzes (
    quiz_id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id),
    title VARCHAR(255), -- e.g., "Calculus II - Midterm Prep"
    topic VARCHAR(100), -- e.g., "Linear Algebra"
    difficulty VARCHAR(50), -- e.g., "Undergraduate BSc"
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Questions Table: The actual content generated by Gemini
--  Persistence
CREATE TABLE IF NOT EXISTS questions (
    question_id SERIAL PRIMARY KEY,
    quiz_id INTEGER REFERENCES quizzes(quiz_id),
    question_text TEXT NOT NULL,
    options JSONB, -- Stores the MCQ options array
    correct_answer TEXT NOT NULL,
    solution_explanation TEXT, -- [cite: 71] Step-by-Step Proof
    metadata_tags TEXT -- [cite: 81] For Topic Strength Analysis
);

-- Attempts/Analytics Table: Tracks student performance
-- [cite: 76] Performance Overview: Accuracy and History
CREATE TABLE IF NOT EXISTS attempts (
    attempt_id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id),
    quiz_id INTEGER REFERENCES quizzes(quiz_id),
    score INTEGER,
    total_questions INTEGER,
    time_spent_seconds INTEGER, -- [cite: 83] Time metrics
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);